### ISSUE TITLE
adding URL to HTTP auth popup window

### ISSUE THREAD

**Issue by schmittlauch** [cloutierjo/titleUrl#11]
When websites request username & password e.g. via http basic auth a popup window is shown by Firefox. Currently it doesn't contain the URL in its title bar, the domain name of the website requesting the login is displayed in the popup text though (but this can't be matched by KeepassXC).

Is it possible to modify the pop ups titlebar or don't web extensions allow that?

**Comment by stonecrusher** [comment]
Sounds like [keepassHTTPconnector](https://addons.mozilla.org/en-US/firefox/addon/keepasshttp-connector/) could help you.
https://github.com/smorks/keepasshttp-connector

**Comment by schmittlauch** [comment]
Given former vulnerabilities of the HTTP interface of password managers allowing eavesdropping I want to avoid using that and think of AutoType being more secure.
So the question still holds whether the newe WebExtension API even allows modifying the window title or whether @stonecrusher's solution is the only one.

**Comment by cloutierjo** [comment]
This is a duplicate of issue #1. To answer your question directly, no web extension doesn't allow to change the pop up the title and I believe there is little chance that such feature will be added in the future. Maybe there is more chance for a workaround from the keepass side, something like looking to the parent windows title when the active windows is a modal.
