### ISSUE TITLE
Feature request: Optionally remove trailing slash

### ISSUE THREAD

**Issue by thenlich** [cloutierjo/titleUrl#13]
There should be an option to show only hostname without trailing slash (even when protocol is hidden)

**Comment by stonecrusher** [comment]
It was just added to prevent phishing (see #3). Maybe he'll still make an option for it.

Author said 5 months ago:
> On the longer term [the] goal I have is to provide a complete title customization similar to some former add-ons, but this isn't planned in the short term for me.

**Comment by cloutierjo** [comment]
Closing as I won't give a direct option to reduce security of the extension. If more complete title customization is done it should be possible for someone to remove it, but until then, even if it's not a perfect security feature it's better to have it.

**Comment by thenlich** [comment]
I decided to publish a modified version which removes the trailing slash: https://addons.mozilla.org/en-US/firefox/addon/titleurl_th/
