### ISSUE TITLE
request add trailing slash in short url format

### ISSUE THREAD

**Issue by phonphen** [cloutierjo/titleUrl#3]
I have a little request, to include the trailing slash in url format:

https://accounts.google.com/

Instead of:

http://accounts.google.com

Because the second form is prone to auto-phishing as it also can match:

http://accounts.google.community-hack.net

**Comment by cloutierjo** [comment]
included in release 0.2

**Comment by phonphen** [comment]
thank you

**Comment by thenlich** [comment]
I still can't see how this would safely prevent phishing, as a malicious host can set the page title to any string, including "MyPhishingPage - http://accounts.google.com/...". The only thing preventing such a phishing attack is to use a password manager which supports wildcard/regular expression matching so a pattern like 'title ends in " - http://accounts.google.com"' can be used.

**Comment by stonecrusher** [comment]
You're right, it doesn't prevent phishing safely. But eliminates one possibility.

I personally use a custom separator like `## MatchURL: ` which is also matched by the password manager and makes an accidential match *very* unlikely.
