### ISSUE TITLE
Keep the port, if in the url

### ISSUE THREAD

**Issue by rwese** [cloutierjo/titleUrl#4]
It would help to identify special sites using alternative ports.

**Comment by cloutierjo** [comment]
Could you show me some URL that doesn't show the port number when it's present in the URL? I did try some that I use myself and the port number is shown in the title bar: 

![port in title](https://cloud.githubusercontent.com/assets/3165230/24799079/5b07c33c-1b67-11e7-8394-e523be8ba36c.png)

**Comment by rwese** [comment]
You are right, I am sorry for my mistake! This issue can be closed.
